docs: customdiff.{ValidateChange,ForceNewIfChange,ComputedIf} take a context.Context
hashicorp/terraform-plugin-sdk pull request #1022
Opened 2022-08-08 20:30 UTC by andrewsomething

These functions all take a `context.Context` as their first argument now.

https://github.com/hashicorp/terraform-plugin-sdk/blob/9bdb216a4ab835003a624b0a15ac39c58ef2861e/helper/customdiff/validate.go#L12

https://github.com/hashicorp/terraform-plugin-sdk/blob/2f7133b9729bf59bd8a59e006f15e4f845556284/helper/customdiff/condition.go#L15

https://github.com/hashicorp/terraform-plugin-sdk/blob/2f7133b9729bf59bd8a59e006f15e4f845556284/helper/customdiff/condition.go#L11

2022-08-26 17:26 UTC, bflad requested changes
Hi @andrewsomething 👋 Thank you for finding and fixing these. You are certainly correct that there is now an additional `context.Context` parameter required in v2, however the location of this parameter is within the anonymous function definitions themselves, not the wrapping function that takes an attribute key and then the function definition. 👍 

Here are some real world examples to help highlight this as well:

https://github.com/hashicorp/terraform-provider-aws/blob/abe4b515dfaf9ab167a336b9552306114097b440/internal/service/configservice/configuration_aggregator.go#L36

https://github.com/hashicorp/terraform-provider-aws/blob/5c7a69d0fc9e2af9151d3ceab390580cc22c6203/internal/service/ssm/parameter.go#L121

Once these changes are made, we can pull this in. Thanks!

2022-08-26 17:26 UTC, bflad commented on helper/customdiff/compose.go
> +//             customdiff.ValidateChange(ctx context.Context, "size", func (old, new, meta interface{}) error {
```suggestion
//             customdiff.ValidateChange("size", func (ctx context.Context, old, new, meta interface{}) error {
```

2022-08-26 17:26 UTC, bflad commented on helper/customdiff/compose.go
> +//             customdiff.ForceNewIfChange(ctx context.Context, "size", func (old, new, meta interface{}) bool {
```suggestion
//             customdiff.ForceNewIfChange("size", func (ctx context.Context, old, new, meta interface{}) bool {
```

2022-08-26 17:26 UTC, bflad commented on helper/customdiff/compose.go
> +//             customdiff.ComputedIf(ctx context.Context, "version_id", func (d *schema.ResourceDiff, meta interface{}) bool {
```suggestion
//             customdiff.ComputedIf("version_id", func (ctx context.Context, d *schema.ResourceDiff, meta interface{}) bool {
```

2022-08-26 17:26 UTC, bflad commented on website/docs/plugin/sdkv2/resources/customizing-differences.mdx
> +            customdiff.ValidateChange(ctx context.Context, "size", func (old, new, meta interface{}) error {
```suggestion
            customdiff.ValidateChange("size", func (ctx context.Context, old, new, meta interface{}) error {
```

2022-08-26 17:26 UTC, bflad commented on website/docs/plugin/sdkv2/resources/customizing-differences.mdx
> +            customdiff.ForceNewIfChange(ctx context.Context, "size", func (old, new, meta interface{}) bool {
```suggestion
            customdiff.ForceNewIfChange("size", func (ctx context.Context, old, new, meta interface{}) bool {
```

2022-08-26 21:12 UTC, andrewsomething commented
:facepalm:  Good catch, updated and rebased to fix the merge conflicts.

2022-08-28 17:03 UTC, bflad approved these changes
Looks good to me 🚀

2022-08-28 17:04 UTC, merged