fix: add path to error when list has too many or few items
hashicorp/terraform-plugin-sdk pull request #826
Opened 2021-11-30 23:57 UTC by josh-barker

This PR adds the resource path to error messages when a list type either has too many or too few elements.

2022-03-12 17:41 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-plugin-sdk?pullRequest=826)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-plugin-sdk?pullRequest=826)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-plugin-sdk?pullRequest=826).</sub>

2022-08-26 18:11 UTC, bflad requested changes
Hi @josh-barker 👋 Thank you for submitting this and apologies for the delayed review.

This partially relates to some of the discussion in https://github.com/hashicorp/terraform/issues/31575, so therefore I think this adjustment is acceptable because even if Terraform added the attribute path information to the diagnostic output, it would only show up in newer versions of Terraform while this would cover all cases of Terraform 0.12 and later when providers update their SDK version to one containing this change.

Would you be able to rebase this and ensure the unit testing is passing? Once that is done, we can get this in. Thanks again.

2022-08-29 12:32 UTC, bflad approved these changes
Looks good to me 🚀  Thanks so much, @josh-barker

2022-08-29 12:32 UTC, merged

2022-08-29 23:45 UTC, josh-barker commented
You're welcome @bflad ! 🙂